GET https://localhost:7157/api/users
###
GET https://localhost:7157
###
GET https://localhost:7157/api/users/2
###
POST https://localhost:7157/api/users
Content-Type: application/json

{
    "FirstName": "Fabrice",
    "LastName": "Orgrick",
    "Email":"fab@gmail.com",
    "Password":"Test1234@"
}

###
PUT https://localhost:7157/api/users/2
Content-Type: application/json

{
    "FirstName": "Fabrice",
    "LastName": "Kouonang"
}

###
DELETE https://localhost:7157/api/users/1