GET https://localhost:7157/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyIiwiZW1haWwiOiJmYWJAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6IkZhYnJpY2UiLCJleHAiOjE3NzM2NzQ4ODgsImlzcyI6IkFwaVByb2pldEJvcnJvd2luZyIsImF1ZCI6IkFwaVByb2pldEJvcnJvd2luZ1VzZXJzIn0.wr4bsIJzFsjjo9MvE1aE8eT6XvlVAKWHjJxeA0sxL0A
###
GET https://localhost:7157
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyIiwiZW1haWwiOiJmYWJAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6IkZhYnJpY2UiLCJleHAiOjE3NzM2NzQ4ODgsImlzcyI6IkFwaVByb2pldEJvcnJvd2luZyIsImF1ZCI6IkFwaVByb2pldEJvcnJvd2luZ1VzZXJzIn0.wr4bsIJzFsjjo9MvE1aE8eT6XvlVAKWHjJxeA0sxL0A
###
GET https://localhost:7157/api/users/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyIiwiZW1haWwiOiJmYWJAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6IkZhYnJpY2UiLCJleHAiOjE3NzM2NzQ4ODgsImlzcyI6IkFwaVByb2pldEJvcnJvd2luZyIsImF1ZCI6IkFwaVByb2pldEJvcnJvd2luZ1VzZXJzIn0.wr4bsIJzFsjjo9MvE1aE8eT6XvlVAKWHjJxeA0sxL0A
###
POST https://localhost:7157/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyIiwiZW1haWwiOiJmYWJAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6IkZhYnJpY2UiLCJleHAiOjE3NzM2NzQ4ODgsImlzcyI6IkFwaVByb2pldEJvcnJvd2luZyIsImF1ZCI6IkFwaVByb2pldEJvcnJvd2luZ1VzZXJzIn0.wr4bsIJzFsjjo9MvE1aE8eT6XvlVAKWHjJxeA0sxL0A

{
    "FirstName": "Fabrice",
    "LastName": "Orgrick",
    "Email":"fab@gmail.com",
    "Password":"Test1234@"
}

###
PUT https://localhost:7157/api/users/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyIiwiZW1haWwiOiJmYWJAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6IkZhYnJpY2UiLCJleHAiOjE3NzM2NzQ4ODgsImlzcyI6IkFwaVByb2pldEJvcnJvd2luZyIsImF1ZCI6IkFwaVByb2pldEJvcnJvd2luZ1VzZXJzIn0.wr4bsIJzFsjjo9MvE1aE8eT6XvlVAKWHjJxeA0sxL0A

{
    "FirstName": "Fabrice",
    "LastName": "Kouonang"
}

###
DELETE https://localhost:7157/api/users/1