//Remplacer avec un token valide pour les tests d'authentification
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJhZG1pbkB0ZXN0LmNvbSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJGYWJyaWNlIiwiZXhwIjoxNzczNzczMjA0LCJpc3MiOiJBcGlQcm9qZXRCb3Jyb3dpbmciLCJhdWQiOiJBcGlQcm9qZXRCb3Jyb3dpbmdVc2VycyJ9.u4KES6TNtTn3IfhoxMr0x1ZilYTeQvPFyXOILFYms8Y

GET https://localhost:7157/api/users
Authorization: Bearer {{token}}
###
GET https://localhost:7157
Authorization: Bearer {{token}}
###
GET https://localhost:7157/api/users/2
Authorization: Bearer {{token}}
###

POST https://localhost:7157/api/users
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "FirstName": "Fabrice",
    "LastName": "Orgrick",
    "Email":"fab@gmail.com",
    "Password":"Test1234@"
}

###
PUT https://localhost:7157/api/users/2
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "FirstName": "Fabrice",
    "LastName": "Kouonang"
}

###
DELETE https://localhost:7157/api/users/1